#!/bin/sh

echo "🔍 Running pre-commit hook to check the code looks good... 🔍"

if ! pnpm typecheck; then
    echo "❌ Type checking failed! Please review TypeScript types."
    echo "Once you're done, don't forget to add your changes to the commit! 🚀"
    exit 1
fi

if ! pnpm lint; then
    echo "❌ Linting failed! 'pnpm lint:fix' will help you fix the easy ones."
    echo "Once you're done, don't forget to add your beautification to the commit! 🤩"
    exit 1
fi

echo "👍 All good! Committing changes..."
